import parentAvatar from "@/icons/parentAvatar.png";
import {
  GRADE,
  PAYMENT_STATUS,
  RELATIONSHIP_DATA,
  USER_STATUS,
} from "@/utils/enum";
import studentAvatar from "@/icons/avatar.png";
export const PARENT_TABLE_HEADER = [
  {
    label: "Parent Name",
    sort: true,
  },
  // {
  //   label: "Kid Name",
  //   sort: true,
  // },
  {
    label: "User ID",
  },
  // {
  //   label: "Kid's Grade",
  // },
  {
    label: "Relation to Kid",
  },
  {
    label: "Registered On",
    sort: true,
  },
  {
    label: "Subscription Status",
  },
  {
    label: "Status",
  },
  {
    label: "Action",
  },
];

export const PARENT_DATA = [
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.UNPAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "XYZ456",
    relation: RELATIONSHIP_DATA.MOTHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.UNPAID,
    status: USER_STATUS.InActive,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
  {
    avatar: parentAvatar,
    name: "Bob Smith",
    userId: "ABC123",
    relation: RELATIONSHIP_DATA.FATHER,
    registeredOn: 1740032661,
    subscriptionStatus: PAYMENT_STATUS.PAID,
    status: USER_STATUS.ACTIVE,
    // student: {
    //   avatar: studentAvatar,
    //   name: "John Doe",
    //   grade: GRADE[10],
    // },
  },
];
