import studentAvatar from "@/icons/avatar.png";
import parentAvatar from "@/icons/parentAvatar.png";
import {
  GRADE,
  RELATIONSHIP_DATA,
  ROADMAP_STATUS,
  USER_STATUS,
} from "@/utils/enum";

export const tableHeader = [
  {
    label: "Student Name ",
    sort: true,
  },
  {
    label: "Parent Name",
    sort: true,
  },
  {
    label: "User ID",
  },
  {
    label: "Grade",
  },
  {
    label: "Registered On",
    sort: true,
  },
  {
    label: "Roadmap Status",
  },
  {
    label: "Status",
  },
  {
    label: "Action",
  },
];

export const roadMapTableHeader = [
  {
    label: "Roadmap Started On",
    sort: true,
  },
  {
    label: "Career Tags",
  },
  {
    label: "Industry Tags",
  },
  {
    label: "Strengths Tags",
  },
  {
    label: "Soft Skills Tags",
  },
  {
    label: "Progress Percentage",
  },
];

export const studentTableData = [
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 1,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.ROADMAP_REQUESTED,
    status: USER_STATUS.ACTIVE,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: 1736919828,
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 2,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.SIGNED_UP,
    status: USER_STATUS.InActive,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 3,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.PAYMENT_DONE,
    status: USER_STATUS.ACTIVE,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 4,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.ROADMAP_REQUESTED,
    status: USER_STATUS.InActive,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 5,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.SIGNED_UP,
    status: USER_STATUS.ACTIVE,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 6,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.SIGNED_UP,
    status: USER_STATUS.ACTIVE,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 7,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.PAYMENT_DONE,
    status: USER_STATUS.InActive,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 8,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.ROADMAP_REQUESTED,
    status: USER_STATUS.ACTIVE,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 9,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.ROADMAP_REQUESTED,
    status: USER_STATUS.ACTIVE,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: "1736919828",
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
  {
    avatar: studentAvatar,
    firstName: "John ",
    lastName: "Doe",
    userId: 10,
    grade: GRADE[10],
    registeredOn: 1736919828,
    roadMapStatus: ROADMAP_STATUS.ROADMAP_REQUESTED,
    status: USER_STATUS.InActive,
    parent: {
      avatar: parentAvatar,
      firstName: "Bob ",
      lastName: "Smith",
      dob: 1736919828,
      gender: "male",
      relationWithStudent: RELATIONSHIP_DATA.FATHER,
      email: "bobsmith@yopmail.com",
      countryCode: "+1",
      phoneNumber: "3136523250",
    },
    dob: 1736919828,
    gender: "male",
    email: "johndoe@example.com",
    countryCode: "+1",
    phoneNumber: "6465386464",
    roadMapData: [
      {
        startDate: 1736919828,
        careerTags: ["Developer", "Engineer"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Analytical"],
        softSkillsTags: ["Communication"],
        progress: 25,
      },
      {
        startDate: 1736919828,
        careerTags: ["Designer", "Artist"],
        industryTags: ["Information Technology"],
        strengthsTags: ["Creativity"],
        softSkillsTags: ["TeamWork"],
        progress: 50,
      },
      {
        startDate: 1736919828,
        careerTags: ["Researcher", "Scientist"],
        industryTags: ["Scientific Research"],
        strengthsTags: ["Critical Thinking"],
        softSkillsTags: ["LeaderShip"],
        progress: 75,
      },
    ],
  },
];
